version: 2
jobs:
  build-job:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/raz.rocks
    steps:
      - checkout
      - run: echo "Baked repo, time to add frost"
            
  deploy-job:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/raz.rocks
    steps:
      - run:
          name: Copy files via ssh
          command: scp -o StrictHostKeyChecking=no -r ~/raz.rocks/* raz@raz.rocks:/var/www/raz.rocks

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master