version: 2

jobs:
  build:
    steps:
      - checkout
      - run: echo "Baked repo, time to add frost"

deployment:
  production:
    branch: master
    commands:
      - scp -r ~/repo raz@raz.rocks:/var/www/raz.rocks